apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: m3-scaler
spec:
  scaleTargetRef:
    kind: ReplicationController
    name: m3
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

